urtbd/urls.py
from django.conf.urls import patterns, include, url
import xadmin

xadmin.autodiscover()


# Views
from django.contrib.auth.views import login, logout
from regform.views import register, home, rulebook, teams

urlpatterns = patterns(
    '',

    url(r'^$', home, name='home'),
    url(r'rulebook', rulebook, name='rulebook'),
    url(r'teams', teams, name='teams'),
    url(r'tournament/register', register),
    url(r'account/logout', logout),


    ### Includes
    url(r'^admin/', include(xadmin.site.urls)),
    url(r'', include('social_auth.urls')),
)

tournament/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Team(models.Model):
    captain = models.ForeignKey(User)
    name = models.CharField("Team Name", max_length=100, blank=False)

    def __unicode__(self):
        return self.name


class Registration(models.Model):
    user = models.ForeignKey(User)
    team = models.ForeignKey(Team, blank=True, null=True)

    nickname = models.CharField("Game Nick", max_length=100, blank=False)

    def __unicode__(self):
        return self.nickname

tournament/forms.py
from django.forms import ModelForm, ValidationError
from regform.models import Registration


class RegistrationForm(ModelForm):
    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']
        try:
            user = Registration.objects.get(nickname=nickname)
        except Registration.DoesNotExist:
            return nickname
        raise ValidationError(u'%s is already being used!' % nickname)

    class Meta:
        model = Registration
        exclude = ['user', 'team']

tournament/views.py
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from tournament.models import Registration, Team
from django.contrib.auth.decorators import login_required
from tournament.forms import RegistrationForm


def home(request):
    players = Registration.objects.all()
    if request.user.is_authenticated():
        nicknames = Registration.objects.all().filter(user=request.user)

        term_nick = "Register"
        if len(nicknames) > 0:
            term_nick = "Edit Nick"
    else:
        term_nick = ""

    data = {
        'players': players,
        'term_nick': term_nick
    }

    return render_to_response('tournament/home.html', data, context_instance=RequestContext(request))


@login_required
def register(request):
    registrations = Registration.objects.all().filter(user=request.user)
    if len(registrations) > 0:
        registration = registrations[0]
        form = RegistrationForm(instance=registration)
    else:
        form = RegistrationForm()

    if request.method == "POST":
        if len(registrations) > 0:
            registration = registrations[0]
        else:
            registration = Registration(user=request.user)

        form = RegistrationForm(request.POST, instance=registration)
        if form.is_valid():
            form.save()
            return redirect('/')

    return render_to_response('tournament/register.html', {'form': form}, context_instance=RequestContext(request))


def rulebook(request):
    return render_to_response('tournament/rulebook.html', context_instance=RequestContext(request))


def teams(request):
    teams = Team.objects.all()
    return render_to_response('tournament/teams.html', {'teams': teams}, context_instance=RequestContext(request))

tournament/templates/tournament/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>UrTBD Season III</title>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="{{ STATIC_URL }}custom.css" rel="stylesheet" />

    {% block extra_head %} {% endblock %}
</head>
<body>
    {% include 'navigation.html' %}

    {% block content %} {% endblock %}
</body>
</html>

tournament/templates/tournament/home.html
{% extends 'base.html' %}

{% block title %} Season - III {% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="span9">
                <h2>Participants</h2>                
            </div>
            <div class="span3">
                {% if request.user.is_authenticated %}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="span12">
                
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Player Nick</th>
                            <th>Full Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for player in players %}
                        <tr>
                            <td>{{ player.nickname }}</td>
                            <td><a href="http://fb.me/{{ player.user.username }}" target="_BLANK">{{ player.user.first_name }} {{ player.user.last_name }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

tournament/templates/tournament/navigation.html
<div class="navbar navbar-static-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">UrTBD Season III</a>
            <ul class="nav pull-right">
                {% if request.user.is_authenticated %}
                    <li><a href="http://fb.me/{{ request.user.username }}"
                           target="_BLANK">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                    <li><a href="/account/logout?next=/">Sign Out</a></li>
                {% else %}
                    <li><a href="/login/facebook">Sign In with Facebook</a></li>
                {% endif %}
            </ul>
            <ul class="nav">
                <li><a href="/teams">Teams</a></li>
                <li><a href="/rulebook">Rules</a></li>
            </ul>
        </div>
    </div>
</div>

tournament/templates/tournament/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="span4 offset4">
                <div class="well">
                    <form action="/tournament/register" method="post" class="reg-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Save Nick" class="btn btn-primary"/>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $("form input[type=text]#id_nickname").addClass("input-block-level");
        $("form input[type=submit]").addClass("btn-primary btn-block");
        $("form label[for=id_nickname]").css({"font-weight" : "bold", "font-size" : "20px", "line-height" : "125%", "text-align" : "center", "margin" : "10px"});
    </script>

{% endblock %}

tournament/templates/tournament/rulebook.html
{% extends 'base.html' %}

{% block title %} Rulebook {% endblock %}


{% block content %}
    <div class="container">
    	
    	<div class="row">
    		<div class="span9">
    			<h2>Tournament Rulebook</h2>
    		</div>
            <div class="span3" style="padding-top:10px">
            	<a href="static/Season_3_Rulebook.pdf" class="btn btn-primary btn-large btn-block">
            		<span class="icon-download icon-white"></span>
            		Download
            	</a>
            </div>
    	</div>


        <div class="row">
            <div class="span12" style="text-align: justify;">

				<div>
					<h4>Team Format</h4> 
					<ul>
						<li>Each team will consist of 5 players exactly.</li>
						<li>Each team will have one Captain. The tournament officials will maintain communication with the Captains only. Each of the Captains are to convey necessary instructions to their teammates. Captains alone are responsible for their teams.</li>
						<li>In every match, a lineup of only 4 players will be playing. The remaining one player will be kept as a substitute. The substitute player should always be ready to join the game when his team is playing. However, substitutes are not to be kept on the sidebench for more than 2 matches in a row.</li>
					</ul>
				</div>

				<div>
					<h4>Match Format</h4>
					<ul>
						<li>There will be 2 rounds in this tournament; (1) The group matches, and (2) The finals.</li>
						<li>The first round will be of &apos;double-round robin&apos; style. Every team will face all the other teams twice; once in their own home map, and again in the opponent&apos;s home (away) map.</li>
						<li>The gametype of each matches are flexible. Teams can choose any of the three eligible gametypes for their home matches. The eligible gametypes are: Team Survivor, Capture the Flag and Bomb.</li>
						<li>Atleast 10 minutes before each match starts, every team must decide and let the tournament collaborators know which map and gametype they intend to play. Only the maps that are listed in the eligible maps section on this document can be chosen.</li>
						<li>Winning team gets 2 points, losing team gets 0 points and in case of a draw, both teams get 1 point each.</li>
						<li>The champion of the tournament will be decided in the finals. The two teams with highest points will make it to the finals. If there is a tie regarding this, the round-win/loss-ratio will be considered for evaluation.</li>
						<li>The finals will consist of 3 matches; the Home and the Away match of the both teams and a bonus match in a People&apos;s choice map. The team to win at least 2 out of 3 of the matches, wins the finals!</li>
					</ul>
				</div>

				<div>
					<h4>General Rules</h4>
					<ul>
						<li>Each of the games will be conducted by a match referee. During a match, only the players of the competing teams, the referee and the GTV cameraman will be allowed to stay on the server. No one else is allowed to stay on the tournament server.</li>
						<li>The game will be played in “Matchmode Enabled” environment, and players must ensure that they&apos;re game settings are optimized to auto-record the match from the player&apos;s perspective (which by default is enabled). All players are to submit all their demos to the admins when they are asked. Failing to do so will result in disqualification. [It is advised that the players record demos of their matches only, and makes sure their pre-match warmup sessions are left off. Also, we advise that players do not record their matches consecutively, and be able to supply each of the match demos seperately. Manually stop/start the recording, if required]</li>
						<li>Cheating, using hacking tools or taking any kind of unfair advantages in the match is a strictly forbidden. It&apos;ll result in immediate disqualification and severe penalty of the entire team.</li>
						<li>Captains are responsible for their teams, for all conducts of the players (whether they&apos;re following the rules, appearing on the server on proper time, etc...). Specially, the proper maintaining of the schedule has to be ensured by the captain. If your player isn&apos;t present, you call in the substitute. If your substitute is absent, you have to start playing with what you have. Delaying isn&apos;t an option in the tight schedule.</li>
						<li>If any of the critical rules are ignored by any of the players, the match referee reserves the right to terminate that specific player, as per their judgement, during the ongoing match and the team must continue without the terminated player.</li>
						<li>Taking advantage of the Matchmode feature, every team will be allowed to call one timeout every match. The duration of the timeouts will be 2 minutes. Timeouts can be utilized for all purposes, including CI handling or player substitution.</li>
						<li>Substitute players may stay in the server and use the Matchmode /sub feature to make themselves substitutes.</li>
						<li>Connection interruption or other technical problems are to be dealt within the timeout period. If your team has already used up its timeout and any of your players are facing technical problems (i.e. CI), the game shall not be paused. Either the player facing the problem OR the substitute (captain&apos;s call) may attempt to reconnect while the game is still running; otherwise the game will continue without that player.</li>
						<li>You have to use Urban Terror 4.1.1, if you have the old 4.1 version, please update. Also, make sure you already have the custom-maps (if any) being played by any of the opponent teams.</li>
						<li>Rules might change with or without prior notice. Therefore, we&apos;d encourage you to be up-to-date with this document to avoid unexpected difficulties. We&apos;ll follow the ClanBase&apos;s standard tournament rules if any awkward situation arise, which we cannot resolve using the rules defined within this document.</li>
					</ul>
				</div>

				<div>
					<h4>Eligible Maps</h4>
					<ul>
						<li>Abbey</li>
						<li>Algiers</li>
						<li>Austria</li>
						<li>Casa</li>
						<li>Commune</li>
						<li>Company</li>
						<li>Elgin</li>
						<li>Kingdom</li>
						<li>Mandolin</li>
						<li>Prague</li>
						<li>Ramelle</li>
						<li>Riyadh</li>
						<li>Sanc</li>
						<li>Snoppis</li>
						<li>Turnpike</li>
						<li>Uptown</li>
						<li>Arena 2</li>
						<li>Dust2 v2</li>
						<li>Kingpin</li>
						<li>Orbital SL</li>
						<li>Paris v2</li>
						<li>Tohunga B8</li>
					</ul>
				</div>
            </div>
        </div>
    </div>

{% endblock %}

tournament/templates/tournament/teams.html
{% extends 'base.html' %}

{% block title %} Teams {% endblock %}


{% block content %}
    <div class="container">
        <h2>Teams</h2>
        <div class="row">
            {% for team in teams %}
                <div class="span3">
                    <div class="well">
                        <h4>{{ team.name }}</h4>
                        <h6>Captain: <i> {{ team.captain.registration_set.all.0.nickname }} </i></h6>
                        <ul>
                            {% for player in team.registration_set.all %}
                                <li>{{ player.nickname }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}